In [127]:
import numpy as np
import tensorflow as tf

In [128]:
a = tf.constant(5.0) # constant is an op, return a tensor
b = tf.constant(2.0)
print a

Tensor("Const_14:0", shape=(), dtype=float32)


In [129]:
ta = tf.zeros((3,3)) # constant

In [141]:
ta.get_shape().as_list()

[3, 3]

In [122]:
sess = tf.InteractiveSession() # to replact "with tf.Session() as sess:"

In [123]:
print sess.run(a) 
print ta.eval() # i.e. sess.run(ta)

5.0
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [126]:
a = tf.constant(1)
a = tf.constant(2)
sess.run(a)

2

In [37]:
try:
    tf.assign(a, 4)  # cannot assign to constant
except TypeError as e:
    print 'Error', e

Error Input 'ref' of 'Assign' Op requires l-value input


In [80]:
W2 = tf.Variable(tf.ones((2,2)), name="weights")
print type(W2)
print W2.initial_value.eval()
sess.run(W2.initializer)
print W2.eval()
print type(W2)

<class 'tensorflow.python.ops.variables.Variable'>
[[ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.]
 [ 1.  1.]]
<class 'tensorflow.python.ops.variables.Variable'>


In [81]:
W1 = W2
print type(W1)

<class 'tensorflow.python.ops.variables.Variable'>


In [83]:
W2 += 3 * tf.ones_like(W2)  # Do NOT do this!! W2 is Tensor, NOT a Variable anymore
print type(W2)
#tf.assign(W2)
print sess.run(W2)


<class 'tensorflow.python.framework.ops.Tensor'>
[[ 4.  4.]
 [ 4.  4.]]


In [85]:
print type(W1)
W1.eval()

<class 'tensorflow.python.ops.variables.Variable'>


array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

In [93]:
update_W1 = tf.assign_add(W1, tf.ones_like(W1))
print type(update_W1)

<class 'tensorflow.python.framework.ops.Tensor'>


In [118]:
print sess.run(W1.initializer)
print update_W1.eval()

TypeError: matmul() takes at least 2 arguments (0 given)

In [115]:
init_op = tf.initialize_all_variables()
print type(init_op)
sess.run(init_op) # Variables must be initialized before use

<class 'tensorflow.python.framework.ops.Operation'>


In [107]:
a.eval()

AttributeError: 'int' object has no attribute 'eval'

In [52]:
print W2.eval()
print sess.run(W2)

[1 1 1]
[1 1 1]


In [53]:
state.eval()

0.0

In [63]:
state = tf.add(state, 1)

In [64]:
state.eval()

4.0

In [67]:
for _ in range(3):
    state += 1.0 #tf.add(state, 1)
    print state.eval()

8.0
9.0
10.0


In [69]:
x = state + a
type(x)

tensorflow.python.framework.ops.Tensor

In [71]:
x += 1

In [72]:
print x.eval()

16.0


In [73]:
with tf.variable_scope("foo"):
    with tf.variable_scope("bar"):
        v = tf.get_variable("v", [1])

In [74]:
v.name

u'foo/bar/v:0'